testing new update

diff --git a/.github/workflows/update_protobuf.yml b/.github/workflows/update_protobuf.yml
--- a/.github/workflows/update_protobuf.yml
+++ b/.github/workflows/update_protobuf.yml
@@ -13,7 +13,7 @@ on:
 jobs:
   check-and-update:
     # Only do this job on the main repo (and not forks of it).
-    if: github.repository == 'apple/swift-protobuf'
+    ### if: github.repository == 'apple/swift-protobuf'
     runs-on: ubuntu-latest
     # Ensure we have the latest Swift in case Reference can be updated.
     container:
@@ -35,13 +35,30 @@ jobs:
 
     - name: Update Reference Protos
       if: steps.update.outputs.updated == 'true'
+      id: make_reference_protos
       # The Reference/upstream contents is generated from Source/protobuf/protobuf, so
       # update them.
+      #
+      # If this fails, it likely means protobuf and/or abseil have changed and
+      # Package.swift need to be updated. In that case, we'll revert Reference/ and let
+      # the PR get created, it will fail CI, but serve as a notice that something needs
+      # to be done to update things.
       #
       # Note: we could move the work in `make reference` to a helper script and skip the
       # install of Make, but given it shares setup with other targets in the Makefile,
       # not sure it's worth while.
-      run: make reference
+      run: |
+        if ! make reference ; then
+          echo "worked=false" >> $GITHUB_OUTPUT
+          echo "message=WARNING: 'make reference' failed, need fix this PR" >> $GITHUB_OUTPUT
+          echo
+          echo "WARNING: 'make reference' failed, the PR will likely be incomplete."
+          echo
+          git checkout -- Reference
+        else
+          echo "worked=true" >> $GITHUB_OUTPUT
+          echo "message=" >> $GITHUB_OUTPUT
+        fi
 
     - name: Create Pull Request
       if: steps.update.outputs.updated == 'true'
@@ -53,8 +70,11 @@ jobs:
 
           - Update vendored protobuf to ${{ steps.update.outputs.protobuf_tag }}
           - Update vendored abseil to required commit from protobuf_deps.bzl
+
+          ${{ steps.make_reference_protos.outputs.message }}
         branch: automated/update-protobuf-${{ steps.update.outputs.protobuf_tag }}
         delete-branch: true
+        draft: ${{ steps.make_reference_protos.outputs.worked }}
         title: 'Update protobuf to ${{ steps.update.outputs.protobuf_tag }}'
         body: |
           ## Automated Protobuf Update
